apiVersion: v1
kind: Secret
metadata:
  name: mtv-migration-sa-token
  namespace: openshift-mtv
  annotations:
    kubernetes.io/service-account.name: mtv-migration-sa
type: kubernetes.io/service-account-token
